import { Ad, User, Offer, Conversation, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'electronice', name: 'Electronice', icon: 'Laptop', count: 1243, color: 'bg-blue-100 text-blue-600' },
  { id: 'auto', name: 'Auto & Moto', icon: 'Car', count: 892, color: 'bg-orange-100 text-orange-600' },
  { id: 'imobiliare', name: 'Imobiliare', icon: 'Home', count: 567, color: 'bg-green-100 text-green-600' },
  { id: 'moda', name: 'Modă & Frumusețe', icon: 'Shirt', count: 2341, color: 'bg-pink-100 text-pink-600' },
  { id: 'casa', name: 'Casă & Grădină', icon: 'Sofa', count: 789, color: 'bg-yellow-100 text-yellow-600' },
  { id: 'sport', name: 'Sport & Fitness', icon: 'Dumbbell', count: 456, color: 'bg-purple-100 text-purple-600' },
  { id: 'copii', name: 'Copii & Jucării', icon: 'Baby', count: 678, color: 'bg-teal-100 text-teal-600' },
  { id: 'animale', name: 'Animale de Companie', icon: 'PawPrint', count: 234, color: 'bg-rose-100 text-rose-600' },
  { id: 'servicii', name: 'Servicii', icon: 'Wrench', count: 345, color: 'bg-indigo-100 text-indigo-600' },
  { id: 'altele', name: 'Altele', icon: 'MoreHorizontal', count: 1123, color: 'bg-slate-100 text-slate-600' },
];

export const DEMO_USERS: User[] = [
  {
    id: 'u1',
    name: 'Andrei Popescu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=andrei&backgroundColor=b6e3f4',
    rating: 4.8,
    reviewCount: 47,
    adsCount: 12,
    memberSince: 'Ianuarie 2022',
    verified: true,
  },
  {
    id: 'u2',
    name: 'Maria Ionescu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maria&backgroundColor=ffdfbf',
    rating: 4.9,
    reviewCount: 83,
    adsCount: 25,
    memberSince: 'Martie 2021',
    verified: true,
  },
  {
    id: 'u3',
    name: 'Cristian Dumitrescu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cristian&backgroundColor=c0aede',
    rating: 4.5,
    reviewCount: 21,
    adsCount: 8,
    memberSince: 'Iulie 2023',
    verified: false,
  },
  {
    id: 'u4',
    name: 'Elena Marin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena&backgroundColor=d1d4f9',
    rating: 5.0,
    reviewCount: 156,
    adsCount: 41,
    memberSince: 'Octombrie 2020',
    verified: true,
  },
  {
    id: 'u5',
    name: 'Bogdan Vasile',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bogdan&backgroundColor=ffd5dc',
    rating: 4.3,
    reviewCount: 14,
    adsCount: 6,
    memberSince: 'Septembrie 2023',
    verified: false,
  },
];

export const DEMO_ADS: Ad[] = [
  {
    id: 'a1',
    title: 'iPhone 14 Pro Max 256GB – Space Black, ca nou',
    price: 4200,
    negotiable: true,
    category: 'Electronice',
    subcategory: 'Telefoane',
    condition: 'ca-nou',
    description: 'Vând iPhone 14 Pro Max 256GB în culoarea Space Black. Folosit 6 luni, fără zgârieturi, bateria la 97%. Vine cu cutia originală, toate accesoriile și garanție Apple până în decembrie 2024. Motivul vânzării: am primit telefon nou de la serviciu.',
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484429be?w=800&auto=format',
      'https://images.unsplash.com/photo-1696085038694-2a2c7f5fe6c1?w=800&auto=format',
    ],
    location: 'Sector 2, București',
    city: 'București',
    postedAt: '2025-04-26T10:30:00Z',
    views: 342,
    favorites: 28,
    status: 'activ',
    seller: DEMO_USERS[0],
    specs: {
      'Memorie internă': '256 GB',
      'RAM': '6 GB',
      'Culoare': 'Space Black',
      'Garanție': 'Până în dec. 2024',
      'Stare baterie': '97%',
    },
    urgent: false,
  },
  {
    id: 'a2',
    title: 'Bicicletă Trek Marlin 7 – 29", mărimea L',
    price: 3500,
    negotiable: true,
    category: 'Sport',
    subcategory: 'Biciclete',
    condition: 'buna-stare',
    description: 'Bicicletă de munte Trek Marlin 7, model 2022. Utilizată sezonier, bine întreținută. Frâne hidraulice Shimano, furca Rock Shox, viteze Shimano Deore 1x12. Include accesorii: pompă, breloc lumini față-spate.',
    images: [
      'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&auto=format',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format',
    ],
    location: 'Mărăști, Cluj-Napoca',
    city: 'Cluj-Napoca',
    postedAt: '2025-04-25T14:20:00Z',
    views: 189,
    favorites: 15,
    status: 'activ',
    seller: DEMO_USERS[1],
    specs: {
      'Mărime roată': '29"',
      'Cadru': 'L (56 cm)',
      'Material cadru': 'Aluminiu',
      'Viteze': 'Shimano 1x12',
      'An fabricație': '2022',
    },
    urgent: false,
  },
  {
    id: 'a3',
    title: 'Canapea extensibilă 3 locuri – Gri antracit, IKEA',
    price: 1200,
    negotiable: false,
    category: 'Casă & Grădină',
    subcategory: 'Canapele',
    condition: 'buna-stare',
    description: 'Canapea extensibilă IKEA Friheten, 3 locuri, culoare gri antracit. Include spațiu de depozitare. Dimensiuni: 230x151cm. Vânzare din cauza mutării. Livrare disponibilă în Cluj.',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&auto=format',
    ],
    location: 'Florești, Cluj',
    city: 'Cluj-Napoca',
    postedAt: '2025-04-24T09:15:00Z',
    views: 97,
    favorites: 8,
    status: 'activ',
    seller: DEMO_USERS[2],
    specs: {
      'Dimensiuni': '230 x 151 cm',
      'Culoare': 'Gri antracit',
      'Extensibil': 'Da',
      'Depozitare': 'Da',
      'Producător': 'IKEA',
    },
  },
  {
    id: 'a4',
    title: 'MacBook Air M2 2022 – 8GB/256GB, Midnight',
    price: 5800,
    negotiable: true,
    category: 'Electronice',
    subcategory: 'Laptopuri',
    condition: 'ca-nou',
    description: 'MacBook Air cu chip M2, 8GB RAM, 256GB SSD, culoarea Midnight. Cumpărat acum 8 luni, folosit exclusiv acasă. Nu are zgârieturi, bateria la 99 cicluri. Vine cu încărcătorul original 35W MagSafe.',
    images: [
      'https://images.unsplash.com/photo-1611186871525-a4b7f67dcd66?w=800&auto=format',
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format',
    ],
    location: 'Centru, Timișoara',
    city: 'Timișoara',
    postedAt: '2025-04-26T08:00:00Z',
    views: 456,
    favorites: 52,
    status: 'activ',
    seller: DEMO_USERS[3],
    specs: {
      'Procesor': 'Apple M2',
      'RAM': '8 GB',
      'Stocare': '256 GB SSD',
      'Display': '13.6" Liquid Retina',
      'Culoare': 'Midnight',
      'Cicli baterie': '99',
    },
    urgent: true,
  },
  {
    id: 'a5',
    title: 'Jachetă Columbia Gore-Tex mărimea M – Bărbați',
    price: 450,
    negotiable: true,
    category: 'Modă',
    subcategory: 'Jachete',
    condition: 'buna-stare',
    description: 'Jachetă Columbia Gore-Tex, model Arcadia, culoare navy blue, mărimea M. Purtată 2 sezoane, în stare perfectă. Impermeabilă, respirabilă, ușoară. Ideală pentru trekking sau city wear.',
    images: [
      'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&auto=format',
      'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&auto=format',
    ],
    location: 'Brătianu, Iași',
    city: 'Iași',
    postedAt: '2025-04-23T16:45:00Z',
    views: 76,
    favorites: 11,
    status: 'activ',
    seller: DEMO_USERS[4],
    specs: {
      'Mărime': 'M',
      'Culoare': 'Navy Blue',
      'Material': 'Gore-Tex',
      'Sezon': 'Primăvară/Toamnă',
    },
  },
  {
    id: 'a6',
    title: 'PlayStation 5 + 2 controllere + 5 jocuri',
    price: 2800,
    negotiable: true,
    category: 'Electronice',
    subcategory: 'Console',
    condition: 'buna-stare',
    description: 'Vând PS5 disc edition + 2 DualSense controllers (alb + negru) + 5 jocuri: God of War Ragnarök, Spider-Man 2, FIFA 24, Gran Turismo 7, Horizon Forbidden West. Funcționează perfect, achiziționat în 2023.',
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format',
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800&auto=format',
    ],
    location: 'Drumul Taberei, București',
    city: 'București',
    postedAt: '2025-04-22T11:30:00Z',
    views: 621,
    favorites: 87,
    status: 'activ',
    seller: DEMO_USERS[0],
    specs: {
      'Model': 'PS5 Disc Edition',
      'Controllere': '2x DualSense',
      'Jocuri incluse': '5',
      'Stocare': '825 GB',
    },
    urgent: false,
  },
  {
    id: 'a7',
    title: 'VW Golf 7 1.6 TDI 110cp – 2016, 120.000 km',
    price: 12500,
    negotiable: true,
    category: 'Auto',
    subcategory: 'Autoturisme',
    condition: 'buna-stare',
    description: 'VW Golf 7 1.6 TDI, 110 cp, an fabricație 2016, 120.000 km reali. Culoare gri magnetic. Dotări: climatronic, senzori parcare față-spate, navigație, scaune față încălzite. Service la zi, carte service completă.',
    images: [
      'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&auto=format',
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format',
    ],
    location: 'Floreasca, București',
    city: 'București',
    postedAt: '2025-04-21T13:00:00Z',
    views: 1234,
    favorites: 143,
    status: 'activ',
    seller: DEMO_USERS[3],
    specs: {
      'Motor': '1.6 TDI 110 CP',
      'An': '2016',
      'Kilometraj': '120.000 km',
      'Cutie': 'Manuală 6 trepte',
      'Culoare': 'Gri Magnetic',
      'Combustibil': 'Diesel',
    },
  },
  {
    id: 'a8',
    title: 'Mașină de spălat Bosch 8kg, A+++, alb',
    price: 900,
    negotiable: false,
    category: 'Casă & Grădină',
    subcategory: 'Electrocasnice',
    condition: 'buna-stare',
    description: 'Mașină de spălat Bosch Serie 4, 8 kg, clasa A+++, 1200 rotații. Folosită 2 ani, în perfectă stare de funcționare. Vânzare din cauza renovării și achiziției unui model nou. Transport disponibil în Brașov.',
    images: [
      'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format',
    ],
    location: 'Schei, Brașov',
    city: 'Brașov',
    postedAt: '2025-04-20T10:00:00Z',
    views: 245,
    favorites: 19,
    status: 'activ',
    seller: DEMO_USERS[2],
    specs: {
      'Capacitate': '8 kg',
      'Eficiență': 'A+++',
      'Turatie max': '1200 rpm',
      'Producător': 'Bosch',
    },
  },
  {
    id: 'a9',
    title: 'Tricicletă electrică Xiaomi pentru copii 2-5 ani',
    price: 350,
    negotiable: true,
    category: 'Copii',
    subcategory: 'Jucării',
    condition: 'ca-nou',
    description: 'Tricicletă electrică Xiaomi QiCycle, pentru copii între 2 și 5 ani. Folosită de 3 ori, stare impecabilă. Include telecomandă pentru părinți, parbriz și copertină detașabilă.',
    images: [
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format',
    ],
    location: 'Mărimi, Sibiu',
    city: 'Sibiu',
    postedAt: '2025-04-19T15:30:00Z',
    views: 78,
    favorites: 9,
    status: 'activ',
    seller: DEMO_USERS[1],
    specs: {
      'Vârstă recomandată': '2-5 ani',
      'Funcție electrică': 'Da',
      'Telecomandă': 'Da',
      'Culoare': 'Roz',
    },
  },
  {
    id: 'a10',
    title: 'Canon EOS R50 + obiectiv 18-45mm – kit complet',
    price: 3100,
    negotiable: true,
    category: 'Electronice',
    subcategory: 'Foto & Video',
    condition: 'ca-nou',
    description: 'Canon EOS R50 mirrorless, 24.2 MP, 4K video, cu obiectiv RF-S 18-45mm f/4.5-6.3. Cumpărat acum 4 luni, 850 declanșări. Include: geantă transport, 2 acumulatoare, card 64GB SanDisk.',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&auto=format',
    ],
    location: 'Florești, Cluj',
    city: 'Cluj-Napoca',
    postedAt: '2025-04-18T09:45:00Z',
    views: 312,
    favorites: 41,
    status: 'activ',
    seller: DEMO_USERS[4],
    specs: {
      'Rezoluție': '24.2 MP',
      'Video': '4K 30fps',
      'Declanșări': '850',
      'Obiectiv': 'RF-S 18-45mm',
      'Culoare': 'Negru',
    },
  },
  {
    id: 'a11',
    title: 'Apartament 2 camere, 52mp, zona Dacia – Iași',
    price: 75000,
    negotiable: true,
    category: 'Imobiliare',
    subcategory: 'Apartamente vânzare',
    condition: 'buna-stare',
    description: 'Apartament 2 camere, 52 mp utili, etaj 3/4, zona Dacia. Renovat complet în 2021: gresie, parchet, termopane, izolație termică. CT propriu. Fără datorii. Bucătărie mobilată utilată.',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&auto=format',
    ],
    location: 'Dacia, Iași',
    city: 'Iași',
    postedAt: '2025-04-17T11:00:00Z',
    views: 987,
    favorites: 76,
    status: 'activ',
    seller: DEMO_USERS[3],
    specs: {
      'Suprafață': '52 mp',
      'Etaj': '3/4',
      'An construcție': '1985',
      'Renovat': '2021',
      'Centrală': 'Proprie',
    },
  },
  {
    id: 'a12',
    title: 'Set mobilier grădină – masă + 4 scaune ratan',
    price: 780,
    negotiable: true,
    category: 'Casă & Grădină',
    subcategory: 'Mobilier exterior',
    condition: 'buna-stare',
    description: 'Set mobilier grădină din ratan sintetic: masă rotundă Ø120cm + 4 scaune cu perne incluse. Rezistent UV, impermeabil. Ținut în depozit în sezonul rece. Perfect pentru terasă sau grădină.',
    images: [
      'https://images.unsplash.com/photo-1591825729269-caeb344f6df2?w=800&auto=format',
      'https://images.unsplash.com/photo-1600210491892-03d54078cfb7?w=800&auto=format',
    ],
    location: 'Pipera, Ilfov',
    city: 'Ilfov',
    postedAt: '2025-04-16T14:30:00Z',
    views: 134,
    favorites: 22,
    status: 'activ',
    seller: DEMO_USERS[0],
    specs: {
      'Material': 'Ratan sintetic',
      'Masă': 'Rotundă Ø120cm',
      'Scaune': '4 bucăți',
      'Culoare': 'Maro/Bej',
      'Sezon': 'Exterior',
    },
  },
];

export const DEMO_OFFERS: Offer[] = [
  {
    id: 'o1',
    adId: 'a1',
    adTitle: 'iPhone 14 Pro Max 256GB – Space Black, ca nou',
    adImage: 'https://images.unsplash.com/photo-1695048133142-1a20484429be?w=400&auto=format',
    buyerId: 'u3',
    sellerId: 'u1',
    currentAmount: 3800,
    originalPrice: 4200,
    status: 'contraoferta',
    expiresAt: '2025-04-28T10:00:00Z',
    history: [
      { id: 'e1', type: 'oferta', amount: 3500, message: 'Bună ziua! Pot oferi 3500 lei, cash imediat.', byUser: 'buyer', timestamp: '2025-04-26T12:00:00Z' },
      { id: 'e2', type: 'contraoferta', amount: 3900, message: 'Bună! Cel mai jos pot merge la 3900 lei. Telefonul e în stare perfectă.', byUser: 'seller', timestamp: '2025-04-26T15:30:00Z' },
      { id: 'e3', type: 'oferta', amount: 3800, message: '3800 și îl iau azi!', byUser: 'buyer', timestamp: '2025-04-26T16:00:00Z' },
    ],
    createdAt: '2025-04-26T12:00:00Z',
  },
  {
    id: 'o2',
    adId: 'a2',
    adTitle: 'Bicicletă Trek Marlin 7 – 29", mărimea L',
    adImage: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&auto=format',
    buyerId: 'u3',
    sellerId: 'u2',
    currentAmount: 3200,
    originalPrice: 3500,
    status: 'acceptata',
    history: [
      { id: 'e4', type: 'oferta', amount: 3000, message: 'Pot lua weekend-ul ăsta, 3000?', byUser: 'buyer', timestamp: '2025-04-24T10:00:00Z' },
      { id: 'e5', type: 'contraoferta', amount: 3200, message: 'La 3200 mergem, este?', byUser: 'seller', timestamp: '2025-04-24T14:00:00Z' },
      { id: 'e6', type: 'acceptata', byUser: 'buyer', timestamp: '2025-04-24T14:30:00Z' },
    ],
    createdAt: '2025-04-24T10:00:00Z',
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'c1',
    adId: 'a6',
    adTitle: 'PlayStation 5 + 2 controllere + 5 jocuri',
    adImage: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=100&auto=format',
    otherUser: DEMO_USERS[0],
    lastMessage: 'Puteți oferi și livrare prin Curier?',
    lastMessageAt: '2025-04-26T18:00:00Z',
    unread: 2,
    messages: [
      { id: 'm1', fromId: 'u3', fromName: 'Eu', text: 'Bună ziua! Mai este disponibil?', timestamp: '2025-04-26T17:00:00Z', read: true },
      { id: 'm2', fromId: 'u1', fromName: 'Andrei Popescu', text: 'Da, este disponibil!', timestamp: '2025-04-26T17:15:00Z', read: true },
      { id: 'm3', fromId: 'u3', fromName: 'Eu', text: 'Puteți oferi și livrare prin Curier?', timestamp: '2025-04-26T18:00:00Z', read: false },
    ],
  },
  {
    id: 'c2',
    adId: 'a4',
    adTitle: 'MacBook Air M2 2022 – 8GB/256GB, Midnight',
    adImage: 'https://images.unsplash.com/photo-1611186871525-a4b7f67dcd66?w=100&auto=format',
    otherUser: DEMO_USERS[3],
    lastMessage: 'Mulțumesc, o zi bună!',
    lastMessageAt: '2025-04-25T10:30:00Z',
    unread: 0,
    messages: [
      { id: 'm4', fromId: 'u4', fromName: 'Elena Marin', text: 'Bună! Da, mai este disponibil. Vii să îl testezi?', timestamp: '2025-04-25T10:00:00Z', read: true },
      { id: 'm5', fromId: 'u3', fromName: 'Eu', text: 'Mulțumesc, o zi bună!', timestamp: '2025-04-25T10:30:00Z', read: true },
    ],
  },
];

export const CONDITIONS: Record<string, string> = {
  'nou': 'Nou',
  'ca-nou': 'Ca nou',
  'buna-stare': 'Stare bună',
  'uzura-normala': 'Uzură normală',
  'necesita-reparatii': 'Necesită reparații',
};

export const CONDITION_COLORS: Record<string, string> = {
  'nou': 'bg-green-100 text-green-700',
  'ca-nou': 'bg-emerald-100 text-emerald-700',
  'buna-stare': 'bg-blue-100 text-blue-700',
  'uzura-normala': 'bg-yellow-100 text-yellow-700',
  'necesita-reparatii': 'bg-red-100 text-red-700',
};

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('ro-RO', { style: 'currency', currency: 'RON', maximumFractionDigits: 0 }).format(price);
}

export function timeAgo(dateStr: string): string {
  const now = new Date();
  const date = new Date(dateStr);
  const seconds = Math.floor((now.getTime() - date.getTime()) / 1000);
  if (seconds < 60) return 'Acum câteva secunde';
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `Acum ${minutes} min`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `Acum ${hours}h`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `Acum ${days} ${days === 1 ? 'zi' : 'zile'}`;
  return date.toLocaleDateString('ro-RO', { day: 'numeric', month: 'short' });
}
